import {
  BPMN,
  ENGINES,
  FLOW_PARENTS,
  SEQUENCE_FLOW_NODES,
  component,
  inFlowScope,
  isActivityType,
  isEventSubProcessScope,
  isTransactionScope,
  replaceContext,
} from './define.js';
import type { BpmnComponentDefinition, ComponentContext, EngineSupport, EventDefinitionName, ReplaceTarget } from './types.js';

type Kind = 'start' | 'intermediateCatch' | 'intermediateThrow' | 'boundary' | 'end';

const TYPE: Record<Kind, string> = {
  start: BPMN.start,
  intermediateCatch: BPMN.catch,
  intermediateThrow: BPMN.throw,
  boundary: BPMN.boundary,
  end: BPMN.end,
};

function event(spec: {
  id: string;
  title: string;
  kind: Kind;
  eventDefinition?: EventDefinitionName;
  meaning: string;
  use: readonly string[];
  not: readonly string[];
  engine: EngineSupport;
  noneStart?: boolean;
  eventSubProcessOnly?: boolean;
  transactionOnly?: boolean;
  attachTransactionOnly?: boolean;
}): BpmnComponentDefinition {
  const bpmnType = TYPE[spec.kind];
  const boundary = spec.kind === 'boundary';
  const canCreate = (ctx: ComponentContext) => {
    if (spec.transactionOnly) return isTransactionScope(ctx);
    if (spec.eventSubProcessOnly) return isEventSubProcessScope(ctx);
    if (spec.noneStart) return inFlowScope(ctx) && !isEventSubProcessScope(ctx);
    if (spec.attachTransactionOnly) {
      return ctx.attachToBpmnType === BPMN.transaction || ctx.attachToIsTransaction === true || isTransactionScope(ctx);
    }
    return inFlowScope(ctx);
  };
  const canAttach = (ctx: ComponentContext) => {
    if (!boundary) return false;
    if (spec.attachTransactionOnly) {
      return ctx.attachToBpmnType === BPMN.transaction || ctx.attachToIsTransaction === true;
    }
    return isActivityType(ctx.attachToBpmnType);
  };
  const canReplace = (el: ReplaceTarget) => el.bpmnType === bpmnType && canCreate(replaceContext(el));
  return component({
    id: spec.id,
    bpmnType,
    eventDefinition: spec.eventDefinition,
    category: 'events',
    title: spec.title,
    allowedParents: FLOW_PARENTS,
    allowedSources: spec.kind === 'start' || boundary ? [] : SEQUENCE_FLOW_NODES,
    allowedTargets: spec.kind === 'end' ? [] : SEQUENCE_FLOW_NODES,
    canCreate,
    canAttach,
    canReplace,
    semanticMeaning: spec.meaning,
    useFor: spec.use,
    doNotUseFor: spec.not,
    layoutBehavior: boundary
      ? { placement: 'attachToActivityBoundary', exceptionBranch: true }
      : { placement: 'flowNode' },
    engineSupport: spec.engine,
  });
}

export const EVENTS: BpmnComponentDefinition[] = [
  event({
    id: 'start.none',
    title: 'None Start Event',
    kind: 'start',
    noneStart: true,
    meaning: 'The process or subprocess is instantiated with no trigger; a starter or parent starts the token.',
    use: ['ordinary process start', 'embedded subprocess entry', 'manual or API instantiation'],
    not: ['event subprocess start', 'wait for a message or timer to instantiate'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.message',
    title: 'Message Start Event',
    kind: 'start',
    eventDefinition: 'MessageEventDefinition',
    meaning: 'A new instance starts when a named message arrives.',
    use: ['instantiate on inbound message', 'message-start event subprocess'],
    not: ['wait for a message after work has already started — use intermediate catch or boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.timer',
    title: 'Timer Start Event',
    kind: 'start',
    eventDefinition: 'TimerEventDefinition',
    meaning: 'A new instance starts on a date, cycle, or duration.',
    use: ['scheduled process', 'cron / cycle start', 'delayed instantiation'],
    not: ['timeout while an activity is running — use boundary.timer'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.conditional',
    title: 'Conditional Start Event',
    kind: 'start',
    eventDefinition: 'ConditionalEventDefinition',
    meaning: 'A new instance starts when a condition becomes true.',
    use: ['start when a data condition holds', 'conditional event subprocess'],
    not: ['Camunda 8 / Zeebe processes — conditional events are not executable there'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'start.signal',
    title: 'Signal Start Event',
    kind: 'start',
    eventDefinition: 'SignalEventDefinition',
    meaning: 'A new instance starts when a broadcast signal is received.',
    use: ['broadcast instantiation', 'signal-start event subprocess', 'one signal, many listeners'],
    not: ['point-to-point message correlation — use message start'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.error',
    title: 'Error Start Event',
    kind: 'start',
    eventDefinition: 'ErrorEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'An interrupting event subprocess starts when an error is thrown in the enclosing activity.',
    use: ['handle a thrown error in the parent', 'centralized error handling subprocess'],
    not: ['top-level process start', 'timeout — use timer', 'non-interrupting handling — error starts always interrupt'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.escalation',
    title: 'Escalation Start Event',
    kind: 'start',
    eventDefinition: 'EscalationEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'An event subprocess starts when an escalation is thrown in the enclosing activity.',
    use: ['escalation handling subprocess', 'propagate a business escalation inward'],
    not: ['technical errors — use error', 'top-level process start'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.compensation',
    title: 'Compensation Start Event',
    kind: 'start',
    eventDefinition: 'CompensateEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'An event subprocess starts to undo completed work when compensation is triggered.',
    use: ['compensation handler as event subprocess', 'undo a completed subprocess'],
    not: ['cancel an in-flight activity — use boundary or cancel', 'ordinary error handling'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.message.nonInterrupting',
    title: 'Non-interrupting Message Start Event',
    kind: 'start',
    eventDefinition: 'MessageEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'A message starts an event subprocess in parallel; the parent activity keeps running.',
    use: ['side handling on message without aborting the parent', 'non-interrupting event subprocess'],
    not: ['replace the parent token — use interrupting message start'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.timer.nonInterrupting',
    title: 'Non-interrupting Timer Start Event',
    kind: 'start',
    eventDefinition: 'TimerEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'A timer starts an event subprocess in parallel; the parent activity keeps running.',
    use: ['reminder or SLA watch without aborting work', 'periodic side process while parent runs'],
    not: ['abort the activity on timeout — use interrupting timer start or boundary.timer'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.conditional.nonInterrupting',
    title: 'Non-interrupting Conditional Start Event',
    kind: 'start',
    eventDefinition: 'ConditionalEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'A condition starts an event subprocess in parallel with the parent activity.',
    use: ['watch a condition without interrupting the parent'],
    not: ['Camunda 8 / Zeebe', 'aborting on condition — use interrupting conditional start'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'start.signal.nonInterrupting',
    title: 'Non-interrupting Signal Start Event',
    kind: 'start',
    eventDefinition: 'SignalEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'A signal starts an event subprocess in parallel; the parent activity keeps running.',
    use: ['broadcast side handling without aborting the parent'],
    not: ['interrupt the parent on signal — use interrupting signal start'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'start.escalation.nonInterrupting',
    title: 'Non-interrupting Escalation Start Event',
    kind: 'start',
    eventDefinition: 'EscalationEventDefinition',
    eventSubProcessOnly: true,
    meaning: 'An escalation starts an event subprocess in parallel; the parent activity keeps running.',
    use: ['observe an escalation without aborting the parent'],
    not: ['abort on escalation — use interrupting escalation start'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.catch.message',
    title: 'Message Intermediate Catch Event',
    kind: 'intermediateCatch',
    eventDefinition: 'MessageEventDefinition',
    meaning: 'The token waits in sequence until a named message arrives.',
    use: ['wait for a reply after sending', 'resume when a message correlates'],
    not: ['timeout during an activity — use boundary.timer', 'first event of several competitors — use event-based gateway'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.catch.timer',
    title: 'Timer Intermediate Catch Event',
    kind: 'intermediateCatch',
    eventDefinition: 'TimerEventDefinition',
    meaning: 'The token waits in sequence for a duration or date before continuing.',
    use: ['delay between steps', 'wait until a deadline on the happy path'],
    not: ['timeout while an activity is still active — use boundary.timer', 'SLA attached to running work'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.catch.conditional',
    title: 'Conditional Intermediate Catch Event',
    kind: 'intermediateCatch',
    eventDefinition: 'ConditionalEventDefinition',
    meaning: 'The token waits until a data condition becomes true.',
    use: ['wait until a business condition holds'],
    not: ['Camunda 8 / Zeebe', 'timeout — use timer catch'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'intermediate.catch.link',
    title: 'Link Intermediate Catch Event',
    kind: 'intermediateCatch',
    eventDefinition: 'LinkEventDefinition',
    meaning: 'Off-page connector target: the token jumps here from a matching throw link in the same process.',
    use: ['continue after an off-page throw link', 'untangle a long sequence visually'],
    not: ['cross-process communication — use message', 'Camunda 8 / Zeebe — link events are not executable there'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'intermediate.catch.signal',
    title: 'Signal Intermediate Catch Event',
    kind: 'intermediateCatch',
    eventDefinition: 'SignalEventDefinition',
    meaning: 'The token waits in sequence until a broadcast signal is received.',
    use: ['wait for a broadcast', 'resume many waiters from one throw'],
    not: ['point-to-point correlation — use message catch'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.none',
    title: 'None Intermediate Event',
    kind: 'intermediateThrow',
    meaning: 'A milestone on the sequence: the token passes through with no wait and no throw.',
    use: ['named milestone', 'state marker on the happy path'],
    not: ['wait for anything', 'send a message — use throw message'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.throw.message',
    title: 'Message Intermediate Throw Event',
    kind: 'intermediateThrow',
    eventDefinition: 'MessageEventDefinition',
    meaning: 'The token sends a message and continues without waiting for a reply.',
    use: ['notify another participant', 'fire-and-forget message'],
    not: ['wait for a reply — follow with a catch or use send/receive tasks', 'user work — use user task'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.throw.escalation',
    title: 'Escalation Intermediate Throw Event',
    kind: 'intermediateThrow',
    eventDefinition: 'EscalationEventDefinition',
    meaning: 'The token throws an escalation to a catching boundary or event subprocess, then continues.',
    use: ['raise a business escalation mid-flow'],
    not: ['technical failure — use error end', 'abort this path — use error'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.throw.link',
    title: 'Link Intermediate Throw Event',
    kind: 'intermediateThrow',
    eventDefinition: 'LinkEventDefinition',
    meaning: 'Off-page connector source: the token jumps to a matching catch link in the same process.',
    use: ['jump to a catch link', 'avoid a long sequence flow across the diagram'],
    not: ['Camunda 8 / Zeebe', 'message to another pool'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'intermediate.throw.compensation',
    title: 'Compensation Intermediate Throw Event',
    kind: 'intermediateThrow',
    eventDefinition: 'CompensateEventDefinition',
    meaning: 'The token triggers compensation of a completed activity, then continues.',
    use: ['explicitly compensate a completed activity', 'undo a named step'],
    not: ['cancel an in-flight transaction — use cancel end', 'error handling of running work'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'intermediate.throw.signal',
    title: 'Signal Intermediate Throw Event',
    kind: 'intermediateThrow',
    eventDefinition: 'SignalEventDefinition',
    meaning: 'The token broadcasts a signal and continues.',
    use: ['notify many catchers at once', 'process-wide broadcast'],
    not: ['addressed message to one participant — use message throw'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.message',
    title: 'Message Boundary Event',
    kind: 'boundary',
    eventDefinition: 'MessageEventDefinition',
    meaning: 'A message arriving while the activity is active interrupts it and takes the exception flow.',
    use: ['abort work when a cancel-or-update message arrives', 'interrupt on inbound message'],
    not: ['wait for a message after the activity completes — use catch', 'non-aborting watch — use non-interrupting message boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.timer',
    title: 'Timer Boundary Event',
    kind: 'boundary',
    eventDefinition: 'TimerEventDefinition',
    meaning: 'Something happens after or during time while an activity is active.',
    use: ['timeout during activity', 'SLA expiration', 'retry delay attached to running work'],
    not: ['competing future events after the activity has completed', 'happy-path delay between tasks — use intermediate timer catch'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.error',
    title: 'Error Boundary Event',
    kind: 'boundary',
    eventDefinition: 'ErrorEventDefinition',
    meaning: 'An error thrown by the activity interrupts it and takes the exception flow. Always interrupting.',
    use: ['catch a business or technical error from an activity', 'error handler next to the failing work'],
    not: ['timeout — use boundary.timer', 'compensation of completed work'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.escalation',
    title: 'Escalation Boundary Event',
    kind: 'boundary',
    eventDefinition: 'EscalationEventDefinition',
    meaning: 'An escalation from the activity is caught on its border; interrupting variant aborts the activity.',
    use: ['catch an escalation from a subprocess or call', 'business escalation handler'],
    not: ['technical errors — use error boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.conditional',
    title: 'Conditional Boundary Event',
    kind: 'boundary',
    eventDefinition: 'ConditionalEventDefinition',
    meaning: 'A condition becoming true while the activity is active interrupts it.',
    use: ['abort work when a data condition holds'],
    not: ['Camunda 8 / Zeebe', 'timeout — use boundary.timer'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'boundary.signal',
    title: 'Signal Boundary Event',
    kind: 'boundary',
    eventDefinition: 'SignalEventDefinition',
    meaning: 'A broadcast signal while the activity is active interrupts it.',
    use: ['abort work on a broadcast', 'global interrupt attached to running work'],
    not: ['point-to-point message — use message boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.compensation',
    title: 'Compensation Boundary Event',
    kind: 'boundary',
    eventDefinition: 'CompensateEventDefinition',
    meaning: 'Registers a compensation handler for when this activity has completed and compensation is triggered. Does not interrupt.',
    use: ['undo this activity if the process later compensates', 'attach a compensate handler'],
    not: ['timeout during execution', 'catch an in-flight error — use error boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.cancel',
    title: 'Cancel Boundary Event',
    kind: 'boundary',
    eventDefinition: 'CancelEventDefinition',
    attachTransactionOnly: true,
    meaning: 'Catches cancellation of a transaction subprocess and runs the cancel path (with compensation).',
    use: ['handle transaction cancel', 'attach to a bpmn:Transaction'],
    not: ['ordinary subprocess — cancel is only legal on a transaction', 'timeout — use boundary.timer'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'boundary.message.nonInterrupting',
    title: 'Non-interrupting Message Boundary Event',
    kind: 'boundary',
    eventDefinition: 'MessageEventDefinition',
    meaning: 'A message during the activity starts an exception path; the activity keeps running.',
    use: ['side path on message without aborting work', 'notification while a task is open'],
    not: ['abort the activity — use interrupting message boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.timer.nonInterrupting',
    title: 'Non-interrupting Timer Boundary Event',
    kind: 'boundary',
    eventDefinition: 'TimerEventDefinition',
    meaning: 'A timer fires while the activity is active and starts a parallel path; the activity keeps running.',
    use: ['SLA reminder without aborting', 'nudge / escalation watch on running work'],
    not: ['abort on timeout — use interrupting boundary.timer'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.escalation.nonInterrupting',
    title: 'Non-interrupting Escalation Boundary Event',
    kind: 'boundary',
    eventDefinition: 'EscalationEventDefinition',
    meaning: 'An escalation is observed on the border without aborting the activity.',
    use: ['log or notify on escalation while work continues'],
    not: ['abort on escalation — use interrupting escalation boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'boundary.conditional.nonInterrupting',
    title: 'Non-interrupting Conditional Boundary Event',
    kind: 'boundary',
    eventDefinition: 'ConditionalEventDefinition',
    meaning: 'A condition starts a parallel path while the activity keeps running.',
    use: ['watch a condition beside running work'],
    not: ['Camunda 8 / Zeebe', 'abort on condition'],
    engine: ENGINES.c7,
  }),
  event({
    id: 'boundary.signal.nonInterrupting',
    title: 'Non-interrupting Signal Boundary Event',
    kind: 'boundary',
    eventDefinition: 'SignalEventDefinition',
    meaning: 'A signal starts a parallel path; the activity keeps running.',
    use: ['broadcast side path without aborting work'],
    not: ['abort on signal — use interrupting signal boundary'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.none',
    title: 'None End Event',
    kind: 'end',
    meaning: 'This path completes normally. Other tokens in the process continue.',
    use: ['ordinary path completion', 'happy-path end'],
    not: ['kill every token — use terminate', 'throw an error to the parent'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.message',
    title: 'Message End Event',
    kind: 'end',
    eventDefinition: 'MessageEventDefinition',
    meaning: 'This path ends and sends a message.',
    use: ['reply and complete', 'notify another participant as the path finishes'],
    not: ['send a message and continue — use throw message'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.error',
    title: 'Error End Event',
    kind: 'end',
    eventDefinition: 'ErrorEventDefinition',
    meaning: 'This path ends by throwing an error to a catching parent (boundary or event subprocess).',
    use: ['fail the activity/process with a named error', 'propagate a business error upward'],
    not: ['quiet completion — use none end', 'kill all tokens without a catcher — use terminate'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.escalation',
    title: 'Escalation End Event',
    kind: 'end',
    eventDefinition: 'EscalationEventDefinition',
    meaning: 'This path ends by throwing an escalation to a catching parent.',
    use: ['finish this path and escalate'],
    not: ['technical failure — use error end'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.signal',
    title: 'Signal End Event',
    kind: 'end',
    eventDefinition: 'SignalEventDefinition',
    meaning: 'This path ends and broadcasts a signal.',
    use: ['complete and notify many catchers'],
    not: ['addressed message — use message end'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.compensation',
    title: 'Compensation End Event',
    kind: 'end',
    eventDefinition: 'CompensateEventDefinition',
    meaning: 'This path ends and triggers compensation of completed activities in the scope.',
    use: ['finish by compensating the scope'],
    not: ['cancel an open transaction — use cancel end', 'in-flight timeout'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.terminate',
    title: 'Terminate End Event',
    kind: 'end',
    eventDefinition: 'TerminateEventDefinition',
    meaning: 'This path ends and consumes all other tokens in the process instance.',
    use: ['abort the whole instance immediately', 'hard stop after a fatal path'],
    not: ['normal completion of one branch — use none end', 'throw a catchable error — use error end'],
    engine: ENGINES.c8,
  }),
  event({
    id: 'end.cancel',
    title: 'Cancel End Event',
    kind: 'end',
    eventDefinition: 'CancelEventDefinition',
    transactionOnly: true,
    meaning: 'Ends a transaction subprocess by cancelling it; compensation runs, then the cancel boundary is taken.',
    use: ['cancel an open transaction', 'rollback a bpmn:Transaction'],
    not: ['ordinary process or subprocess — cancel end is only legal inside a transaction', 'terminate the whole instance — use terminate'],
    engine: ENGINES.c7,
  }),
];
